### ISSUE TITLE
Translation of static pages to Slovene

### ISSUE THREAD

**Issue by cyplas** [clarinsi/clarin-dspace#9]
Currently, none of the static pages under dspace-xmlui/src/main/webapp/themes/UFAL/lib/html are translated to Slovene (except for dummy.html). I suggest that at least the pages linked to in the clarin.si footer be translated.

**Comment by TomazErjavec** [comment]
The student doing the translation produced the first draft translation (deposit.html).
To see if it is ok I would like to test it on beta. 
Currently, I put in on fado, in the directory /project/lindat-dspace/source/dspace-xmlui/src/main/webapp/themes/UFAL/lib/html/sl 
I guess I would now have to deploy the beta installation for the change to take effect, and before that commit and push to si-master @ https://github.com/clarinsi/clarin-dspace.git as our Wiki says "Warning: upon deployment an automatic git checkout -f si-master is performed, so uncommitted changes are lost!"

However, currently beta is not in a clean state, it has uncommited previous changes, so, @cyplas please commit yours and mine changes, push & deploy so we can see if the translated deposit.html is ok.
(or correct me if I misunderstood something).

**Comment by cyplas** [comment]
Actually, that checkout and warning pertains to lindat-common (/project/lindat/common-theme), not clarin-dspace (/project/lindat/source). Still, I'm trying to keep clarin-dspace clean, so if and when you find that it isn't, then please do pester me. :) I've committed my changes now. Of course the same goes the other way around: if I go on fado and find that the git directory is dirty with html changes, I'll pester you (or mercilessly overwrite your changes :) ).

The canonical way to update the changes is to deploy and restart. But if you're doing this a lot and this becomes tedious and time-consuming, you can "cheat" (on fado only, please) by adding/changing static files directly in the installation path. In this case, the source directory /project/lindat-dspace/source/dspace-xmlui/src/main/webapp/themes/UFAL/lib/html/sl/ corresponds to the installation directory /project/lindat-dspace/installation/webapps/xmlui/themes/UFAL/lib/html/sl/.

I tested the new deposit.html translation, but two things were missing. First, you have to have a corresponding xml file as well, deposit.xml. I've added it. Second, the outermost element should be the `<div>`, not `<html>`. I've stripped the outer tags now. (I figured these things out by looking at the English counterparts.) Now it seems to work: https://beta.clarin.si/repository/xmlui/page/deposit?locale-attribute=sl.

**Comment by TomazErjavec** [comment]
> Actually, that checkout and warning pertains to lindat-common (/project/lindat/common-theme), not clarin-dspace (/project/lindat/source). 

Sorry!

> Still, I'm trying to keep clarin-dspace clean, so if and when you find that it isn't, then please do pester me. :) I've committed my changes now. 

Thanks. Pester: you forgot there (or, and I hope not, just lost connection before saving the latest and correct version) the emacs autosave files, which git sees. 

> Of course the same goes the other way around: if I go on fado and find that the git directory is dirty with html changes, I'll pester you (or mercilessly overwrite your changes :) ).

OK, forwarned... I've now commited the sl/deposit.* files.

> The canonical way to update the changes is to deploy and restart. But if you're doing this a lot and this becomes tedious and time-consuming, you can "cheat" (on fado only, please) by adding/changing static files directly in the installation path. In this case, the source directory /project/lindat-dspace/source/dspace-xmlui/src/main/webapp/themes/UFAL/lib/html/sl/ corresponds to the installation directory /project/lindat-dspace/installation/webapps/xmlui/themes/UFAL/lib/html/sl/.

Thanks, this is useful info. Maybe add it to Wiki?

> I tested the new deposit.html translation, but two things were missing. First, you have to have a corresponding xml file as well, deposit.xml. I've added it. 

Thanks, will remember to translate it myself in the future.

> Second, the outermost element should be the `<div>`, not `<html>`. I've stripped the outer tags now. (I figured these things out by looking at the English counterparts.) 

OK, thanks, this is something the translator put in, I warned her now to be careful. 
Interestingly, the tags you mention don't survive in the notification email I received..

> Now it seems to work: https://beta.clarin.si/repository/xmlui/page/deposit?locale-attribute=sl.

Not really, the images are missing - no fault of yours of course, the translator somehow messed up the `imp/@source` no idea how or why. I asked her to correct them.

However, this brings with it another interesting problem: which images (screenshots) to put in, English or Slovene ones? Of course they should be in Slovene, but:
* If we were to put in the localised screenshot we have to be 100% certain that the translations captured won't change, as updating the screen localisations would then also involve re-doing the screenshots, and we've already found inconsistencies in the translations.
* The Czech have English ones, cf. https://lindat.mff.cuni.cz/repository/xmlui/page/deposit?locale-attribute=cs
* The images don't seem to belong to the localisation directories: `<img src="../themes/UFAL/images/deposit/step1.png" class="print_screen_img" />`

This is probably one of those wider repo i18n issues meant to be taken up in the CLARIN project. Still, maybe an "enhacement" request for the LINDAT folks?

**Comment by cyplas** [comment]
> Thanks, this is useful info. Maybe add it to Wiki?

I've updated the wiki (http://nl.ijs.si/wiki/Administration/StandardProcedures#Making_local_adaptations_of_clarin_45dspace_and_47or_contributing_to_lindat_39s_repository_itself), adding mention of the in-place installation/ editing, as well as notes on non-root committing (your last commit was as root) and edits to the git branch descriptions, which are also relevant here (e.g., be careful of committing to si-master: this branch should (always) be production ready).

> Not really, the images are missing - no fault of yours of course, the translator somehow messed up the imp/@source no idea how or why. I asked her to correct them.

I think this can easily happen if you're developing locally on your laptop and don't have access to fado or a clone and installation of clarin-dspace, as you're probably saving HTML from the browser, which downloads related images etc in a different relative location than clarin-dspace uses ...

> Interestingly, the tags you mention don't survive in the notification email I received..

That's because I didn't escape the tags with backquotes originally, but edited the post afterwards.

> This is probably one of those wider repo i18n issues meant to be taken up in the CLARIN project. Still, maybe an "enhacement" request for the LINDAT folks?

Hmm, I'm not sure, because it's not clear what kind of generic solution is possible, as it would be quite hard to automate snapshot updating. I think it's reasonable for each centre to do this as they think is best. Unless you had something else in mind?

As for the location of any localised images, etc, I would suggest we keep them in the same directory (or perhaps better, a subdirectory) as these localised html and xml files. The alternative would be to create sl/ subdirectories where the English images are kept, but I think this is inferior.

**Comment by TomazErjavec** [comment]
> I've updated the wiki (http://nl.ijs.si/wiki/Administration/StandardProcedures#Making_local_adaptations_of_clarin_45dspace_and_47or_contributing_to_lindat_39s_repository_itself), adding mention of the in-place installation/ editing, as well as notes on non-root committing (your last commit was as root) and edits to the git branch descriptions, which are also relevant here (e.g., be careful of committing to si-master: this branch should (always) be production ready).

Thanks! And sorry for the root, I think I tried it as me but it didn't work. Will investigate on next commit and report if problems.

> > Not really, the images are missing - no fault of yours of course, the translator somehow messed up the imp/@source no idea how or why. I asked her to correct them.
> I think this can easily happen if you're developing locally on your laptop and don't have access to fado or a clone and installation of clarin-dspace, as you're probably saving HTML from the browser, which downloads related images etc in a different relative location than clarin-dspace uses ...

Yes, this is exactly what happened. Now zipped the html, so she can download them clean.

> > This is probably one of those wider repo i18n issues meant to be taken up in the CLARIN project. Still, maybe an "enhacement" request for the LINDAT folks?

> Hmm, I'm not sure, because it's not clear what kind of generic solution is possible, as it would be quite hard to automate snapshot updating. I think it's reasonable for each centre to do this as they think is best. Unless you had something else in mind?

No, I didn't meant automatic screenshot captures, just that the images should by convention also live in the same directory as the localisations, i.e. they are taken to be part of the localisation pack. But maybe this is something we can do on our own for Slovene, once we get that far, regardless of how the Czech folks have it.

> As for the location of any localised images, etc, I would suggest we keep them in the same directory (or perhaps better, a subdirectory) as these localised html and xml files. 

Exactly! Hm, maybe open a new (long lasting) issue on this?

**Comment by TomazErjavec** [comment]
Now most of the static pages are translated and available both on clari.si and beta.
I will leave this issue open anyway, as a couple pages could still be translated.

**Comment by TomazErjavec** [comment]
All the pages have now been translated - in case we missed some, we can re-open this issue, closing for now.
